voteMessage: "You voted :) thanks"
commands: ["kit tools USER","time set day"]
voteLink: "https://vote-website-here.com/"
randomItensVote: true
itensQuantity: 2

randomItensID: ["6:2/64", "6:1/12", "397:1/1", "76/98", "159:15/12", "278/1", "159:5/2", "1/12"]